- name: Install required packages
  apt:
    name:
      - openjdk-11-jdk
      - wget
      - tar
    state: present
  become: yes

- name: Create Kafka user
  user:
    name: "{{ kafka_user }}"
    comment: "Kafka Service Account"
    shell: /bin/bash
  become: yes

- name: Download Kafka
  get_url:
    url: "{{ kafka_download_url }}"
    dest: "/tmp/kafka.tgz"
  become: yes

- name: Extract Kafka
  unarchive:
    src: "/tmp/kafka.tgz"
    dest: "/opt"
    remote_src: yes
    extra_opts: [--strip-components=1]
  become: yes

- name: Set permissions for Kafka directory
  file:
    path: "{{ kafka_install_dir }}"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    state: directory
    mode: "0755"
  become: yes

- name: Configure systemd service for Zookeeper
  template:
    src: "zookeeper.service.j2"
    dest: "/etc/systemd/system/zookeeper.service"
  become: yes
  notify: Restart Zookeeper

- name: Configure systemd service for Kafka
  template:
    src: "kafka.service.j2"
    dest: "/etc/systemd/system/kafka.service"
  become: yes
  notify: Restart Kafka

- name: Start and enable Zookeeper
  systemd:
    name: zookeeper
    enabled: yes
    state: started
  become: yes

- name: Start and enable Kafka
  systemd:
    name: kafka
    enabled: yes
    state: started
  become: yes
