- name: Install required dependencies (Java)
  apt:
    name: openjdk-11-jdk
    state: present
  become: yes

- name: Create Kafka group
  group:
    name: "{{ kafka_group }}"
    state: present
  become: yes

- name: Create Kafka user with home directory
  user:
    name: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    create_home: yes
    shell: /bin/bash
  become: yes

- name: Ensure Kafka home directory exists
  become: yes
  become_user: "{{ kafka_user }}"
  file:
    path: "{{ kafka_home }}"
    state: directory
    mode: '0755'

- name: Download Kafka as kafka user
  become: yes
  become_user: "{{ kafka_user }}"
  get_url:
    url: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    dest: "{{ kafka_tgz }}"

- name: Extract Kafka in home directory
  become: yes
  become_user: "{{ kafka_user }}"
  unarchive:
    src: "{{ kafka_tgz }}"
    dest: "{{ kafka_home }}"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Ensure Kafka config directory exists
  become: yes
  become_user: "{{ kafka_user }}"
  file:
    path: "{{ kafka_config_dir }}"
    state: directory
    mode: '0755'

- name: Configure Kafka with dynamic templates
  become: yes
  become_user: "{{ kafka_user }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ kafka_config_dir }}/{{ item.dest }}"
  loop:
    - { src: "controller.properties.j2", dest: "controller.properties" }
    - { src: "broker.properties.j2", dest: "broker.properties" }
