---
- name: Install JDK
  apt:
    name: openjdk-11-jdk
    state: present
  become: yes

- name: Download Kafka
  get_url:
    url: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    dest: "/home/ubuntu/kafka.tgz"

- name: Extract Kafka
  unarchive:
    src: "/home/ubuntu/kafka.tgz"
    dest: "/home/ubuntu"
    remote_src: yes
    extra_opts: [--strip-components=1]
