- name: Install required packages
  apt:
    name:
      - openjdk-11-jdk
      - wget
      - tar
    state: present
  become: yes

- name: Create Kafka user
  user:
    name: "{{ kafka_user }}"
    comment: "Kafka Service Account"
    shell: /bin/bash
    create_home: no
  become: yes

- name: Ensure Kafka install directory exists
  file:
    path: "{{ kafka_install_dir }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: "0755"
  become: yes

- name: Download Kafka
  get_url:
    url: "{{ kafka_download_url }}"
    dest: "/tmp/kafka.tgz"
    mode: "0644"
    force: yes
  become: yes

- name: Extract Kafka
  unarchive:
    src: "/tmp/kafka.tgz"
    dest: "{{ kafka_install_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
  become: yes

- name: Set permissions for Kafka directory
  file:
    path: "{{ kafka_install_dir }}"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    state: directory
    mode: "0755"
  become: yes

- name: Configure Kafka for Kraft mode
  template:
    src: "server.properties.j2"
    dest: "{{ kafka_install_dir }}/config/server.properties"
  become: yes
  notify: Restart Kafka

- name: Format Kafka Storage for Kraft Mode
  command: "{{ kafka_install_dir }}/bin/kafka-storage.sh format -t {{ kafka_cluster_id }} -c {{ kafka_install_dir }}/config/server.properties"
  become: yes
  become_user: "{{ kafka_user }}"
  args:
    creates: "{{ kafka_install_dir }}/logs/meta.properties"

- name: Configure systemd service for Kafka
  template:
    src: "kafka.service.j2"
    dest: "/etc/systemd/system/kafka.service"
  become: yes
  notify: Restart Kafka

- name: Start and enable Kafka
  systemd:
    name: kafka
    enabled: yes
    state: started
  become: yes
