---
- name: Install required dependencies (Java)
  apt:
    name: openjdk-11-jdk
    state: present
  become: yes

- name: Create Kafka group
  group:
    name: "{{ kafka_group }}"
    state: present
  become: yes

- name: Create Kafka user with home directory
  user:
    name: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    create_home: yes
    shell: /bin/bash
  become: yes

- name: Download Kafka as kafka user
  become: yes
  become_user: "{{ kafka_user }}"
  get_url:
    url: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    dest: "/home/kafka/kafka.tgz"

- name: Extract Kafka in /home/kafka
  become: yes
  become_user: "{{ kafka_user }}"
  unarchive:
    src: "/home/kafka/kafka.tgz"
    dest: "/home/kafka"
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Configure Kafka with dynamic templates
  become: yes
  become_user: "{{ kafka_user }}"
  template:
    src: "{{ item.src }}"
    dest: "/home/kafka/config/kraft/{{ item.dest }}"
  loop:
    - { src: "controller.properties.j2", dest: "controller.properties" }
    - { src: "broker.properties.j2", dest: "broker.properties" }
