---
- name: Install required dependencies (Java)
  apt:
    name: openjdk-11-jdk
    state: present
  become: yes

- name: Create Kafka group
  group:
    name: "{{ kafka_group }}"
    state: present
  become: yes

- name: Create Kafka user
  user:
    name: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    create_home: no
    shell: /bin/bash
  become: yes

- name: Download Kafka
  get_url:
    url: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    dest: "/tmp/kafka.tgz"

- name: Extract Kafka
  unarchive:
    src: "/tmp/kafka.tgz"
    dest: "{{ kafka_install_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
  become: yes

- name: Change ownership of Kafka directory
  file:
    path: "{{ kafka_install_dir }}"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0755'
    recurse: yes
  become: yes

- name: Create Kafka data and log directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0755'
  loop:
    - "{{ kafka_data_dir }}"
    - "{{ kafka_log_dir }}"
  become: yes

- name: Generate Kafka Cluster ID (if not set)
  shell: "{{ kafka_install_dir }}/bin/kafka-storage.sh random-uuid"
  register: cluster_id
  when: kafka_cluster_id == ""

- name: Set Kafka Cluster ID
  set_fact:
    kafka_cluster_id: "{{ cluster_id.stdout if cluster_id.stdout else kafka_cluster_id }}"

- name: Format Storage for KRaft
  command: >
    {{ kafka_install_dir }}/bin/kafka-storage.sh format
    --config {{ kafka_install_dir }}/config/kraft/server.properties
    --cluster-id {{ kafka_cluster_id }}
  become: yes
  become_user: "{{ kafka_user }}"
  args:
    creates: "{{ kafka_data_dir }}/meta.properties"

- name: Configure Kafka for KRaft Mode
  template:
    src: "server.properties.j2"
    dest: "{{ kafka_install_dir }}/config/kraft/server.properties"
  become: yes
  notify: Restart Kafka

- name: Configure Kafka systemd service
  template:
    src: "kafka.service.j2"
    dest: "/etc/systemd/system/kafka.service"
  become: yes

- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: Enable and start Kafka service
  systemd:
    name: kafka
    state: started
    enabled: yes
  become: yes
