kafka_node_id: 1
kafka_version: "3.9.0"
scala_version: "2.13"

# User & Group
kafka_user: "kafka"
kafka_group: "kafka"

# Installation Paths
kafka_home: "/home/{{ kafka_user }}"
kafka_tgz: "{{ kafka_home }}/kafka.tgz"
kafka_config_dir: "{{ kafka_home }}/config/kraft"
